import { assessZoneRisk } from './riskEngine';
import type { CrowdZone, RiskLevel } from './simulationTypes';

const BASE_TIMESTAMP_MS = Date.UTC(2026, 5, 11, 18, 0, 0);
const UPDATE_INTERVAL_MS = 3_000;

export const ZONE_LINKS: { source: string; target: string; maxCapacity: number }[] = [
  // Event 1 (Lucusa Stadium)
  { source: 'north-gate', target: 'east-concourse', maxCapacity: 80 },
  { source: 'gate-c', target: 'east-concourse', maxCapacity: 60 },
  { source: 'west-entrance', target: 'east-concourse', maxCapacity: 70 },
  // Event 2 (City Arena)
  { source: 'main-entry-gate', target: 'south-concourse', maxCapacity: 120 },
  { source: 'north-gate-stand', target: 'south-concourse', maxCapacity: 100 },
  // Event 3 (Downtown Fan Zone)
  { source: 'transit-egress-gate', target: 'screening-plaza', maxCapacity: 150 },
  { source: 'screening-plaza', target: 'food-&-beverage-court', maxCapacity: 140 },
];

const initialZoneInputs = [
  {
    id: 'north-gate',
    name: 'North Gate',
    type: 'gate' as const,
    capacity: 2000,
    density: 72,
    queueLength: 184,
    entryRate: 46,
    exitRate: 34,
    status: 'open' as const,
  },
  {
    id: 'east-concourse',
    name: 'East Concourse',
    type: 'concourse' as const,
    capacity: 5000,
    density: 54,
    queueLength: 96,
    entryRate: 31,
    exitRate: 38,
    status: 'open' as const,
  },
  {
    id: 'gate-c',
    name: 'Gate C',
    type: 'gate' as const,
    capacity: 1500,
    density: 86,
    queueLength: 248,
    entryRate: 58,
    exitRate: 29,
    status: 'open' as const,
  },
  {
    id: 'west-entrance',
    name: 'West Entrance',
    type: 'gate' as const,
    capacity: 1800,
    density: 41,
    queueLength: 64,
    entryRate: 24,
    exitRate: 33,
    status: 'open' as const,
  },
];

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function round(value: number): number {
  return Math.round(value);
}

export function getSimulationTimestamp(tick: number): string {
  return new Date(BASE_TIMESTAMP_MS + tick * UPDATE_INTERVAL_MS).toISOString();
}

function zoneWave(zoneId: string, tick: number, offset = 0): number {
  const idSeed = [...zoneId].reduce((total, char) => total + char.charCodeAt(0), 0);
  return Math.sin((tick + offset + idSeed / 13) * 0.72);
}

export function createInitialCrowdZones(): CrowdZone[] {
  const timestamp = getSimulationTimestamp(0);

  return initialZoneInputs.map((zone) => {
    const nextZone = {
      ...zone,
      type: zone.type as 'gate' | 'concourse',
      risk: 'LOW' as RiskLevel,
      lastUpdated: timestamp,
    };
    return {
      ...nextZone,
      risk: assessZoneRisk(nextZone, timestamp).risk,
    };
  });
}

export function simulateNextCrowdZones(previousZones: CrowdZone[], tick: number, isEvacuationActive?: boolean): CrowdZone[] {
  const timestamp = getSimulationTimestamp(tick);
  
  // Clone previous zones to compile updates
  const nextZones: CrowdZone[] = previousZones.map((z) => ({
    ...z,
    // Reset dynamics that get accumulated from links
    entryRate: 0,
    exitRate: 0,
    status: z.status || 'open',
    capacity: z.capacity || (z.type === 'gate' ? 2000 : 5000),
  }));

  // Step 1: External Arrivals (Queuing at Gates)
  nextZones.forEach((zone) => {
    if (zone.type !== 'gate') return;

    // Base incoming flow generated by wave curves
    const rawArrival = 40 + zoneWave(zone.id, tick, 0) * 15;
    let baseArrival = round(clamp(rawArrival, 10, 80));

    if (isEvacuationActive) {
      baseArrival = 0; // Inflow shut down completely
    }

    if (zone.status === 'open') {
      zone.queueLength = round(clamp(zone.queueLength + baseArrival, 0, 800));
    } else {
      // If gate is closed, people stack up or get rerouted
      if (zone.detourTargetId) {
        const detourTarget = nextZones.find((t) => t.id === zone.detourTargetId);
        if (detourTarget) {
          // Reroute 60% of arrivals to the detour target
          detourTarget.queueLength = round(clamp(detourTarget.queueLength + baseArrival * 0.6, 0, 800));
          zone.queueLength = round(clamp(zone.queueLength + baseArrival * 0.4, 0, 800));
        } else {
          zone.queueLength = round(clamp(zone.queueLength + baseArrival, 0, 800));
        }
      } else {
        zone.queueLength = round(clamp(zone.queueLength + baseArrival, 0, 800));
      }
    }
    // Set entryRate as the arrivals to the gate queue
    zone.entryRate = baseArrival;
  });

  // Step 2: Flow along links
  const activeLinks = ZONE_LINKS.filter(
    (link) => nextZones.some((z) => z.id === link.source) && nextZones.some((z) => z.id === link.target)
  );

  activeLinks.forEach((link) => {
    const src = nextZones.find((z) => z.id === link.source)!;
    const tgt = nextZones.find((z) => z.id === link.target)!;

    if (src.status === 'closed' || tgt.status === 'closed') {
      return;
    }

    if (isEvacuationActive) {
      // In evacuation, flow is reversed (concourse -> gate exit)
      if (src.type === 'gate') {
        const peopleInConcourse = (tgt.density * (tgt.capacity || 5000)) / 100;
        const flow = round(clamp(Math.min(peopleInConcourse * 0.35 + 30, link.maxCapacity * 2.5), 0, peopleInConcourse));

        tgt.exitRate = (tgt.exitRate || 0) + flow;
        src.entryRate = (src.entryRate || 0) + flow;
        src.exitRate = (src.exitRate || 0) + flow; // Drains to safety out of gate
      } else {
        const peopleCount = (src.density * (src.capacity || 2000)) / 100;
        const flow = round(clamp(Math.min(peopleCount * 0.35 + 25, link.maxCapacity * 2.0), 0, peopleCount));

        src.exitRate = (src.exitRate || 0) + flow;
        tgt.entryRate = (tgt.entryRate || 0) + flow;
      }
      return;
    }

    // Check backpressure (if target concourse is near capacity, reduce flow rate)
    const backpressure = tgt.density > 80 ? Math.max(0, 1 - (tgt.density - 80) / 20) : 1.0;

    let flow = 0;
    if (src.type === 'gate') {
      // Move from gate queue to concourse
      flow = Math.min(src.queueLength * 0.25 + 15, link.maxCapacity) * backpressure;
      flow = round(clamp(flow, 0, src.queueLength));

      src.queueLength = Math.max(0, src.queueLength - flow);
      src.exitRate = flow; // Exit rate from gate queue
    } else {
      // Move from concourse to concourse
      const peopleCount = (src.density * (src.capacity || 2000)) / 100;
      flow = Math.min(peopleCount * 0.15 + 10, link.maxCapacity) * backpressure;
      flow = round(clamp(flow, 0, peopleCount));

      src.exitRate = (src.exitRate || 0) + flow;
    }

    tgt.entryRate = (tgt.entryRate || 0) + flow;
  });

  // Step 3: Evacuation / Exiting the Venue
  // Concourses that have no outgoing links drain out of the venue (exit rate)
  nextZones.forEach((zone) => {
    const hasOutgoingLink = activeLinks.some((l) => l.source === zone.id);
    if (zone.type === 'concourse' && !hasOutgoingLink) {
      const exitShift = zoneWave(zone.id, tick, 2) * 8;
      let baseExit = round(clamp(40 + exitShift, 15, 95));
      
      if (isEvacuationActive) {
        baseExit = baseExit * 2.5; // High outflow evacuation clearance
      }

      const peopleInConcourse = (zone.density * (zone.capacity || 5000)) / 100;
      const exitFlow = round(Math.min(peopleInConcourse, baseExit));

      zone.exitRate = (zone.exitRate || 0) + exitFlow;
    }
  });

  // Step 4: Apply Density Updates based on computed entry/exit pressure
  nextZones.forEach((zone) => {
    let pressure = 0;
    if (zone.type === 'gate') {
      if (isEvacuationActive) {
        zone.queueLength = Math.max(0, zone.queueLength - zone.exitRate);
        pressure = -zone.exitRate;
      } else {
        const baseArrival = zone.entryRate; // Stored baseArrival from Step 1
        const flow = zone.exitRate;         // Stored flow from Step 2
        pressure = baseArrival - flow;
      }

      // Update entryRate to reflect the actual rate passing through the gate into the stadium
      zone.entryRate = isEvacuationActive ? 0 : zone.exitRate;
    } else {
      pressure = zone.entryRate - zone.exitRate;
    }
    const densityDelta = pressure * 0.08 + (isEvacuationActive ? 0 : zoneWave(zone.id, tick, 4) * 2.4);
    zone.density = round(clamp(zone.density + densityDelta, 0, 98));
  });

  // Step 5: Final checks & Risk Assessments
  return nextZones.map((zone) => {
    // If evacuation is active, force risks to elevated postures
    const assessment = assessZoneRisk(zone, timestamp);
    const resolvedRisk = isEvacuationActive 
      ? (zone.density > 50 ? 'critical' : zone.density > 20 ? 'high' : 'medium')
      : assessment.risk;

    return {
      ...zone,
      lastUpdated: timestamp,
      risk: resolvedRisk as any,
    };
  });
}
