from enum import Enum


class UserRole(str, Enum):  # noqa: UP042 - Preserve existing serialized enum behavior.
    SUPER_ADMIN = "SUPER_ADMIN"
    GLOBAL_OPERATIONS_DIRECTOR = "GLOBAL_OPERATIONS_DIRECTOR"
    STADIUM_MANAGER = "STADIUM_MANAGER"
    SECURITY_SUPERVISOR = "SECURITY_SUPERVISOR"
    MEDICAL_COORDINATOR = "MEDICAL_COORDINATOR"
    VOLUNTEER_COORDINATOR = "VOLUNTEER_COORDINATOR"
    DATA_ANALYST = "DATA_ANALYST"
    VIEWER = "VIEWER"
