from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.agents.orchestrator import get_all_pending_decisions
from app.auth.dependencies import require_role
from app.auth.roles import UserRole
from app.services.action_executor import execute_approved_action, get_execution_history
from app.services.learning_engine import get_learning_records, log_learning_record
from app.services.vision_intelligence import assess_camera_feed

router = APIRouter(tags=["autonomous_operations"])

# In-memory global state for autonomous mode
_autonomous_mode = {"enabled": False}


class DecisionApproval(BaseModel):
    operatorName: str = "mock-operator"


class VisionAssessRequest(BaseModel):
    cameraId: str
    zone: str
    estimatedPeople: int
    density: str


class AutonomousModeRequest(BaseModel):
    enabled: bool


@router.get("/api/autonomous/decisions")
@router.get("/api/v1/autonomous/decisions")
def list_pending_decisions():
    """Retrieve all active recommendations generated by orchestrator agents."""
    return {"status": "success", "data": get_all_pending_decisions()}


@router.post(
    "/api/autonomous/decisions/{decision_id}/approve",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
@router.post(
    "/api/v1/autonomous/decisions/{decision_id}/approve",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
def approve_decision(decision_id: str, payload: DecisionApproval):
    """Approves a pending decision and executes the approved action immediately."""
    try:
        res = execute_approved_action(decision_id, payload.operatorName)
        # Log learning feedback loop automatically
        log_learning_record(
            action=f"{res['actionType']} ({res['target']})",
            outcome=res["impact"],
            score=92,
        )
        return {"status": "success", "data": res}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


@router.post(
    "/api/autonomous/decisions/{decision_id}/reject",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
@router.post(
    "/api/v1/autonomous/decisions/{decision_id}/reject",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
def reject_decision(decision_id: str):
    """Rejects a pending decision, canceling execution."""
    return {"status": "success", "message": f"Decision {decision_id} successfully rejected."}


@router.get("/api/autonomous/history")
@router.get("/api/v1/autonomous/history")
def list_execution_history():
    """Retrieves list of all executed actions."""
    return {"status": "success", "data": get_execution_history()}


@router.get("/api/autonomous/learning")
@router.get("/api/v1/autonomous/learning")
def list_learning_records():
    """Retrieves lists of historical reinforcement learning outcome records."""
    return {"status": "success", "data": get_learning_records()}


@router.post("/api/vision/assess")
@router.post("/api/v1/vision/assess")
def run_vision_assessment(payload: VisionAssessRequest):
    """Assess CCTV camera counts and return crowd density risk levels."""
    res = assess_camera_feed(
        payload.cameraId,
        payload.zone,
        payload.estimatedPeople,
        payload.density,
    )
    return {"status": "success", "data": res}


@router.post(
    "/api/autonomous/mode",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
@router.post(
    "/api/v1/autonomous/mode",
    dependencies=[
        Depends(
            require_role(
                UserRole.GLOBAL_OPERATIONS_DIRECTOR, UserRole.STADIUM_MANAGER, UserRole.SUPER_ADMIN
            )
        )
    ],
)
def toggle_autonomous_mode(payload: AutonomousModeRequest):
    """Toggles global state of autonomous operations monitoring."""
    _autonomous_mode["enabled"] = payload.enabled
    return {"status": "success", "data": _autonomous_mode}


@router.get("/api/autonomous/mode")
@router.get("/api/v1/autonomous/mode")
def get_autonomous_mode():
    """Retrieves global state of autonomous operations monitoring."""
    return {"status": "success", "data": _autonomous_mode}
